version: '3.4'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P2ssword
    ports:
      - "1433:1433"
  api:
    build: .
    container_name: rest-api-net
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=2023
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/API.pfx
    ports:
      - "8081:443"
    volumes:
    - ~/.aspnet/https:/https:ro
  
    
    